"""initial_schema

Revision ID: 898f1855f677
Revises: 
Create Date: 2026-09-04 01:53:28.615330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898f1855f677'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('source_document', sa.String(length=255), nullable=False),
    sa.Column('rule_clause_reference', sa.String(length=150), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('applicability_conditions', sa.JSON(), nullable=False),
    sa.Column('validation_type', sa.Enum('PRESENCE', 'REGEX_MATCH', 'NUMERIC_RANGE', 'STANDARD_UNITS', 'FONT_HEIGHT', 'DATE_VALIDITY', 'CUSTOM_LOGIC', name='validationtype'), nullable=False),
    sa.Column('validation_parameters', sa.JSON(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='ruleseverity'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_rule_id'), 'rules', ['rule_id'], unique=True)
    op.create_index(op.f('ix_rules_version'), 'rules', ['version'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.Enum('INSPECTOR', 'REVIEWER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('badge_number', sa.String(length=50), nullable=True),
    sa.Column('zone_division', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_code', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('package_type', sa.String(length=100), nullable=False),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'PENDING_REVIEW', 'COMPLETED', 'FLAGGED', 'ARCHIVED', name='inspectionstatus'), nullable=False),
    sa.Column('overall_status', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'NEEDS_REVIEW', name='overallstatus'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('officer_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_category'), 'inspections', ['category'], unique=False)
    op.create_index(op.f('ix_inspections_inspection_code'), 'inspections', ['inspection_code'], unique=True)
    op.create_index(op.f('ix_inspections_reference_id'), 'inspections', ['reference_id'], unique=False)
    op.create_table('inspection_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('image_type', sa.Enum('PDP', 'BACK', 'ADDITIONAL', name='imagetype'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('quality_status', sa.Enum('GOOD', 'ACCEPTABLE', 'BLURRY', 'GLARE', 'LOW_RESOLUTION', 'UNASSESSED', name='imagequalitystatus'), nullable=False),
    sa.Column('quality_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_code', sa.String(length=100), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.Enum('FORM_II_STATUTORY_NOTICE', 'COMPLIANCE_CERTIFICATE', 'VIOLATION_DOSSIER', name='reporttype'), nullable=False),
    sa.Column('generated_by_id', sa.String(length=36), nullable=False),
    sa.Column('summary_data', sa.JSON(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_report_code'), 'reports', ['report_code'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.Enum('ACCEPT_ALL', 'EDIT_DECLARATION', 'REJECT_DECLARATION', 'OVERRIDE_VERDICT', 'SIGN_OFF', name='reviewactiontype'), nullable=False),
    sa.Column('previous_status', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'NEEDS_REVIEW', name='overallstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'NEEDS_REVIEW', name='overallstatus'), nullable=True),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('result', sa.Enum('PASS', 'FAIL', 'NEEDS_REVIEW', 'NOT_APPLICABLE', name='complianceresult'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_image_id', sa.String(length=36), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_image_id'], ['inspection_images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_findings_field'), 'compliance_findings', ['field'], unique=False)
    op.create_index(op.f('ix_compliance_findings_result'), 'compliance_findings', ['result'], unique=False)
    op.create_table('declarations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspection_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_image_id', sa.String(length=36), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DETECTED', 'VERIFIED', 'REJECTED', 'EDITED', name='declarationstatus'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_image_id'], ['inspection_images.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_declarations_field_name'), 'declarations', ['field_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_declarations_field_name'), table_name='declarations')
    op.drop_table('declarations')
    op.drop_index(op.f('ix_compliance_findings_result'), table_name='compliance_findings')
    op.drop_index(op.f('ix_compliance_findings_field'), table_name='compliance_findings')
    op.drop_table('compliance_findings')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_reports_report_code'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('inspection_images')
    op.drop_index(op.f('ix_inspections_reference_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspection_code'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_category'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rules_version'), table_name='rules')
    op.drop_index(op.f('ix_rules_rule_id'), table_name='rules')
    op.drop_table('rules')
    # ### end Alembic commands ###
